# Stage 1:
FROM node:14-alpine as builder

WORKDIR /app

COPY package*.json ./

COPY . .

RUN npm run build

# Stage 2
FROM node:14-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD [ "node", "dist/index.js" ]
