version: '3.8'
services:
    backend: 
        build: ./example-backend
        environment:
            REDIS_HOST: redis
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
            REQUEST_ORIGIN: http://localhost:80
        depends_on:
            - redis
            - postgres
        networks:
            - mynetwork
    frontend:
        build: ./example-frontend
        environment:
            REACT_APP_BACKEND_URL: http://localhost:80
        networks:
            - mynetwork
    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - ./redis:/data
        networks:
            - mynetwork
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DATABASE: postgres
        volumes:
            - ./database:/var/lib/postgresql/data
        networks:
            - mynetwork
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - mynetwork
            
networks:
  mynetwork: